### ISSUE TITLE
Opening RAF (Fujifilm raw) crashes after caching 

### ISSUE THREAD

**Issue by didiergm** [aferrero2707/PhotoFlow#99] opened 2016-06-27 15:23 UTC
Version 1:2.6+git20160627-564 dowloaded today from photoflow-git (not photoflow-gtk-git3) 

When I open a RAF file the display is fairly quick (about 8-10 seconds) then the indicator at the bottom of the main windows reads 'caching' this step takes between 30 and 45 seconds

This is what I get on the launch window towards the end : 
and when that message "memory: high-water mark 67,35 MB" the program exits w/o message or warning; 

Before start I had over 2.3 Gb available

VipsRegion (object), base class, VipsRegion: 0x7f4938013960, im = 0x7f4952741e20, left = 0, top = 0, width = 0, height = 0
20 VipsArea alive
        0x7f495161a740 count = 1, bytes = 2820
        0x7f4951606fc0 count = 1, bytes = 8
        0x7f49515ffd10 count = 1, bytes = 32
        0x7f4951735a30 count = 6, bytes = 2820
        0x7f495160ee80 count = 2, bytes = 2820
        0x7f49527645c0 count = 1, bytes = 2820
        0x7f4952758d30 count = 1, bytes = 8
        0x7f4952752f30 count = 2, bytes = 8
        0x7f495274c7d0 count = 2, bytes = 8
        0x7f49527459d0 count = 1, bytes = 8
        0x7f49506fc9a0 count = 2, bytes = 8
        0x7f49506fb910 count = 2, bytes = 8
        0x7f49506e65a0 count = 2, bytes = 8
        0x7f49506e0400 count = 2, bytes = 8
        0x7f49506fec20 count = 17, bytes = 748
        0x7f49506fded0 count = 17, bytes = 1168
        0x7f49506f72c0 count = 32, bytes = 1168
        0x7f49506ce870 count = 32, bytes = 748
        0x7f49506ceda0 count = 32, bytes = 32
        0x7f49506c8940 count = 32, bytes = 786420
memory: 72 allocations, 10336072 bytes
files: 7 open
memory: high-water mark 67,35 MB

**Comment by aferrero2707** [comment] 2016-06-27 22:22
Indeed the X-trans demosaicing still contains some bugs, and I can confirm the crash. I'm investigating the issue.

Thanks for reporting this!

**Comment by didiergm** [comment] 2016-06-27 22:37
Not a problem Sir, it seems normal that it still wet round the ears; 

Other people have reported a fairly difficult bug to reproduce on the Linux version (can't say for the others) : when clicking too rapidly on various icons PhF freezes as if caought in an endless loop. I know this report is flaky at best but be aware that there is something not quite right . I'll try to reproduce but have not succeeded so far

**Comment by aferrero2707** [comment] 2016-06-28 08:24
The freezes look more like a thread synchronisation problem... I'll try to reproduce that as well, but it's certainly more difficult.

**Comment by aferrero2707** [comment] 2016-06-29 12:37
I have traced down the reason for the crash with the X-trans demosaicing, now I need to implement a proper fix. Hopefully I will push a new version in few days from now.

**Comment by didiergm** [comment] 2016-06-29 12:38
That's excellent news! Thanks for your efforts

**Comment by aferrero2707** [comment] 2016-06-29 13:41
I've just pushed a fix on github, the crash should be completely solved now.

**Comment by didiergm** [comment] 2016-06-29 13:42
Ok, I'll wait for the ppa to be updated and report back

**Comment by aferrero2707** [comment] 2016-08-01 13:46
Did you have a chance to test the latest X-trans demosaicing? If it is not crashing anymore, then I'd like to close this issue...

Thanks!

**Comment by didiergm** [comment] 2016-08-01 15:22
Unfortunately not, my machine crashed and I won't have time to do any test
before next week, but this is high on my todo list

**Comment by aferrero2707** [comment] 2016-08-01 15:29
No problem, I just wanted to make sure I did not miss something...
Good luck!

**Comment by richo67** [comment] 2016-08-04 11:02
I have discovered PhotoFlow only few days ago, went through the video tutorial. I am using fuji cameras. I wonder if the build is ready in ppa as I have no possibility to install. Thank you for your answer.

**Comment by aferrero2707** [comment] 2016-08-04 11:06
@richo67 The "photoflow-git" Ubuntu package in the "Highly Explosive" PPA is already up-to-date and includes support for demosaicing Fuji files. But you say "I have no possibility to install". Which distribution are you using?

**Comment by richo67** [comment] 2016-08-04 11:59
@aferrero2707 Thank you for the pointer to the ppa. I have added to my ElementaryOS (based in ubuntu) and I have installed old (latest official) photoflow. It led not to the crash but lengthy loading and incorrect rendering image with something like vertical scan lines. When I install "photoflow-git" it loads RAF file very quickly and correctly.  I can confirm that for RAF files from fujiflm X-T1 it worked well.

What doesn't work is image from FujiFilm X-E2S:

```
CameraMetaData::getCamera(): id="FUJIFILMX-E2S"
RawSpeed:Unable to find camera in database: FUJIFILM X-E2S 
[rawspeed] Camera 'FUJIFILM' 'X-E2S', mode '' not supported, and not allowed to guess. Sorry.
new_raw_image->get_nref(): 1
Error: signal 11:

```

The rest of this note is possible abut somethings else. I would appreciate if you can help me with that as rendering of user interface is pretty bad. Also it is pity that you moved to different way in user interface from the one showed in your tutorial video. I found that one much better than this with small icons and all in same side (very confusing same as darktable is).

However the build ("photoflow-git") has such a colors that I can not read many text at interface elements. I am getting following error. I wanted to send screen shot but I am for whatever reason not able to.

`(photoflow:16433): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",`

I have also tried to install 'photoflow-gtk3-git'  which looks better, but still not perfect. getting following warnings:

```
Calling ImageProcessor::instance().run()
ImageProcessor started.
Loading theme file /usr/share/photoflow/themes/photoflow-dark.css

(photoflow:16792): Gtk-WARNING **: Theme parsing error: photoflow-dark.css:126:12: Not using units is deprecated. Assuming 'px'.

```

**Comment by aferrero2707** [comment] 2016-08-06 09:45
@richo67 The FujiFilm X-E2S seems to be too new for the RawSpeed version currently used by photoflow... I'll see if I can quickly update to get it supported.

Concerning the user interface: which video tutorial are you referring to? Just to know which version of the UI it is showing, since this has been evolving over time...
I agree that the UI is still perfectible, and different people have different preferences. At some point I want to make the widget arrangement configurable, with two or three options proposed to the user in the preferences, so that I can better meet the various personal preferences.

Concerning the error about the "pixmap" engine, could you try to install the "gtk2-engines-pixbuf" and "gtk2-engines-murrine" packages? Hopefully the UI will then look better...

**Comment by richo67** [comment] 2016-08-07 12:24
@aferrero2707 I answered both UI questions of yours in other thread associated with issue #102

**Comment by aferrero2707** [comment] 2017-07-30 14:30
I'm closing this issue because the initial problem with RAF images was fixed. The additional issue about UI colors/layout will stay open as a suggestion for enhancement.

**Closed by aferrero2707** 2017-07-30 14:30 UTC
Labels: bug
