### ISSUE TITLE
AppImage: Segmentation fault (core dumped) on openSUSE Leap 42.2

### ISSUE THREAD

**Issue by probonopd** [aferrero2707/PhotoFlow#148] opened 2017-06-24 10:50 UTC
```
linux@linux:~> /home/linux/Downloads/PhotoFlow-20170623_2216-git-linear_gamma-1ef45898a283c9efebd6588a0959364eafdf3dd3.glibc2.14-dbg.glibc2.14-x86_64.AppImage 
Segmentation fault (core dumped)

linux@linux:~> cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.2"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.2"
PRETTY_NAME="openSUSE Leap 42.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

Removing the following libraries solves the segfault:

```
removed './usr/lib/x86_64-linux-gnu/libc.so.6'
removed './usr/lib/x86_64-linux-gnu/libdl.so.2'
removed './usr/lib/x86_64-linux-gnu/libm.so.6'
removed './usr/lib/x86_64-linux-gnu/libpthread.so.0'
removed './usr/lib/x86_64-linux-gnu/libresolv.so.2'
removed './usr/lib/x86_64-linux-gnu/librt.so.1'
removed './usr/lib/x86_64-linux-gnu/libstdc++.so.6'
removed './usr/lib/x86_64-linux-gnu/libxcb.so.1'
removed './usr/lib/x86_64-linux-gnu/libX11.so.6'
```

**Comment by aferrero2707** [comment] 2017-06-24 11:00
How to debug this? It seems to be crashing directly in the AppRun code, as nothing gets printed on the terminal.

Any idea?

**Comment by probonopd** [comment] 2017-06-24 11:02
Bundling the mentioned `libc.so.6` related libraries is known to segfault. Please do not bundle them. Then it works, I have tested it.

**Comment by aferrero2707** [comment] 2017-06-24 18:25
You are absolutely right, there was a mistake in the script that creates the AppImage bundle, and the list of blacklisted libraries was not read correctly.

I have corrected the appimage.sh scripts for both the stable and linear_gamma branches, hopefully the appimages now work properly.

Thanks!

**Comment by aferrero2707** [comment] 2017-07-30 13:50
I'm closing this since it should be fixed in the current AppImage packages. Please re-open the issue in case the problem is still there.

Thanks!

**Closed by aferrero2707** 2017-07-30 13:50 UTC
