### ISSUE TITLE
some problems under ubuntu 14.04

### ISSUE THREAD

**Issue by revast** [aferrero2707/PhotoFlow#47] opened 2015-10-20 13:55 UTC
1: Interface does not come up when not adding an image at startup. qt 5.3.2. It builds up the frames, but then disappears.
2: when adding image, it comes up, but tools sidebar to the right is missing, and there is no way to get it???
3: /usr/share/photoflow/themes/photoflow-dark.gtkrc:580: error: invalid string constant "notebook-close", expected valid string constant
no other errors in debug output...

does not matter whether I am using dhor/myway or anton+/photo-video-apps ppas

**Comment by aferrero2707** [comment] 2015-10-20 16:58
1: could you try starting photoflow from the terminal, and copy/paste the console messages? I've never observed such misbehavior...

2: to open the toolbar on the right you need to double-click on the name of some layer on the left. This will open the widget with the corresponding controls on the right (see [here](http://photoflowblog.blogspot.fr/2015/08/new-photoflow-release-020-is-out-with.html) for details). Did you try that already?

3: to be fixed, but not "dangerous"...

**Comment by revast** [comment] 2015-10-20 19:46
photoflow
exePath: /usr/bin
exePath: /usr/bin
Starting image processor...
ImageProcessor::ImageProcessor(): starting thread
ImageProcessor::ImageProcessor(): thread started
Image processor started.
locale dir: /usr/share/locale
Calling ImageProcessor::instance().run()
ImageProcessor started.
stat_result=0
/usr/share/photoflow/themes/photoflow-dark.gtkrc:580: error: invalid string constant "notebook-close", expected valid string constant


nothing special... right now I experienced the same behaviour when adding a filepath behind. mnext time I tried it worked

**Comment by aferrero2707** [comment] 2015-10-20 21:01
It could indeed be a WM issue... at least I have now some direction to go to investigate the issue. However, I need to get my hands on an XFce box first. I've tested the app with Mate and Cinnamon under Mint 17 and it works, although some other user reported issues with the theme when using Cinnamon under Ubuntu.

**Comment by aferrero2707** [comment] 2015-10-21 12:49
It could indeed be a WM issue... at least I have now some direction to go to investigate the issue. However, I need to get my hands on an XFce box first. I've tested the app with Mate and Cinnamon under Mint 17 and it works, although some other user reported issues with the theme when using Cinnamon under Ubuntu.

**Comment by Joermungand** [comment] 2015-10-30 12:30
I am not on Ubuntu, but on Arch with the latest XFCE. The window _eventually_ comes up, but only after xfwm4 segfaults. It turns out the problem lies with the gtkrc theme. If I remove it everything works just fine.

**Comment by aferrero2707** [comment] 2015-10-30 19:38
I've just tested with Xfce under Ubuntu 14.04, and I have no problems running photoflow with the custom theme... do you have the murrine theme engine installed in your system? It is needed by the custom theme, but it is not included in the package dependencies (it should probably be added...).

**Comment by Joermungand** [comment] 2015-10-30 19:51
The murrine engine is installed all right. However, running the package in Openbox will not trigger a segfault or any other error apart from the "notebook-close" one, which is probably due to the fact that the corresponding section in the gtkrc has been commented out, so the notebook-close style is no longer defined.

**Comment by Joermungand** [comment] 2015-10-31 16:45
Inching closer. It seems that what pisses off xfwm4 is the event sent in main.cc. I’ve built PhotoFlow with the line containing ‘gdk_event_send_clientmessage_toall’ (line 212 in main.cc) edited out. The results: xfwm4 no longer segfaults while the custom theme is appropriately applied. Same behaviour on Openbox.

**Comment by aferrero2707** [comment] 2015-10-31 18:27
I have tried to comment out this line in my Mint 17 system, and the custom theme gets still loaded as well... I took this line from some GTK example, but maybe it is not really necessary after the call to `Gtk::RC::reparse_all()`.

I will leave it commented in the stable branch, to see if other users eventually report a regression on other systems.

**Comment by Joermungand** [comment] 2015-10-31 18:33
Apparently, it isn’t – rather detrimental. I’ve absolutely no experience with GTK programming, so I’ve no clue about how it is actually supposed to work. I’ll update the PKGBUILD, see what gives.

**Comment by aferrero2707** [comment] 2015-11-04 18:18
Removing the call to `gdk_event_send_clientmessage_toall()` seems to fix things under Xfce without bad side effects, so I'll close the issue as solved.

**Closed by aferrero2707** 2015-11-04 18:18 UTC
