### ISSUE TITLE
Artefacts along image edges after latest commit to stable

### ISSUE THREAD

**Issue by Joermungand** [aferrero2707/PhotoFlow#91] opened 2016-05-04 16:15 UTC
After the latest commit to the stable branch, raw images load very quickly, but artefacts show up along all image edges (same as in issue #58, which I filed back in December).

**Comment by aferrero2707** [comment] 2016-05-05 10:00
I'm looking into that...

**Comment by aferrero2707** [comment] 2016-05-05 12:18
I cannot reproduce the issue with the current stable branch. Could you provide me a sample RAW file for which the problem appears?

Also, do you have just artefacts or also extra black margins, like in issue #58? If there are only artefacts but no extra margin, then the reason is a remaining bug in the fast demosaicing routine I am using to render RAW images at zoom levels below 1:1. I'll fix that before next release.

Thanks!

**Comment by Joermungand** [comment] 2016-05-05 12:46
It happens with any RAW image I’m trying to open. There are no extra 
black margins, only the artefacts, and they do disappear when zooming at 
1:1. They are Canon CR2 files. Here’s a link to a sample off Dropbox:

https://www.dropbox.com/s/m4r0yawuw52z719/IMG_3602.CR2?dl=0

**Comment by aferrero2707** [comment] 2016-05-05 13:28
Then this issue is only related with the fast demosaicing, not with RawSpeed itself... I'll try to push a fix this evening.

Moreover, the artefact does not affect exported images.

**Comment by Joermungand** [comment] 2016-05-05 13:37
Right, exported images are OK.

**Comment by aferrero2707** [comment] 2016-05-05 18:17
It should be fixed in the stable branch, as well as a similar corrupted border issue with the IGV demosaicing.

**Comment by Joermungand** [comment] 2016-05-05 19:30
Fixed! Tahnks! Pushed to AUR.

**Comment by aferrero2707** [comment] 2016-05-05 19:31
Great! The I close the issue.

**Closed by aferrero2707** 2016-05-05 19:31 UTC
