### ISSUE TITLE
Compilation error - GIT version

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#90] opened 2016-04-18 09:51 UTC
Take a look at:

https://launchpadlibrarian.net/254203061/buildlog_ubuntu-trusty-amd64.photoflow-gtk3-git_1%3A2.6+git20160417-492~ubuntu14.04.1_BUILDING.txt.gz

Something broke few days ago. Do we need a more fresh VIPS? (8.2.1is used for 14.04, 8.2.2 for 16.04).

**Comment by aferrero2707** [comment] 2016-04-18 10:05
This seems to be a duplicate of issue #89, i.e. a missing <cstring> include.

I've pushed the fix to the stable branch few minutes ago.

Thanks!

**Closed** 2016-07-01 08:27 UTC
Labels: bug
