### ISSUE TITLE
batch mode - windows 10 - PhotoFlow 0.2.8

### ISSUE THREAD

**Issue by phweyland** [aferrero2707/PhotoFlow#154] opened 2017-08-11 18:28 UTC
Starting the following command in the folder where the nef and pfp files are, PhotoFLow seems to exit without doing anything. 

> "C:\Program Files (x86)\PhotoFlow\photoflow-0.2.8\bin\photoflow.exe" --batch 20170715_Chartres_012.NEF default.pfp PFf\\%name%.jpg

The following command opens the nef file.

> "C:\Program Files (x86)\PhotoFlow\photoflow-0.2.8\bin\photoflow.exe" 20170715_Chartres_012.NEF

**Comment by phweyland** [comment] 2017-08-12 11:30
My mistake !
` exit without doing anything` ... Yes, the command exits immediatly but Photoflow executes in background and the jpg is correctly created some time later.
Will that work in batch loop on all images of the source folder ?

**Comment by aferrero2707** [comment] 2017-08-15 20:00
Looks like the processing thread gets detached from the main process... very strange, I will try to reproduce the problem and get back here as soon as I have some progress.

**Comment by aferrero2707** [comment] 2017-08-29 17:12
I cannot reproduce such a behavior with wine under Linux... not having a Win10 system at hand, I'm a bit lost.

Could you post the full terminal output of the above btach command?

Thanks!

**Comment by phweyland** [comment] 2017-08-30 16:22
Here is the output:

D:\Documents\Images\Photos\2010\2017\20170701_Chartres>"C:\Program Files (x86)\PhotoFlow\photoflow-0.2.8\bin\photoflow.exe" --batch 20170715_Chartres_002.NEF default.pfp PFf\%name%.jpg
D:\Documents\Images\Photos\2010\2017\20170701_Chartres>

But the image is actually created:
![image](https://user-images.githubusercontent.com/23012047/29883217-d66c3372-8daf-11e7-8f87-5de1437c8cee.png)

Would that work with GBD ?J

**Comment by aferrero2707** [comment] 2017-08-30 16:30
If I understand correctly, the program goes immediately in the background without producing any terminal output, right?

There might be some windows-specific thing I am missing...

**Comment by aferrero2707** [comment] 2017-08-30 16:44
Wait a moment... I think I probably found the reason for this strange behaviour. I am compiling the windows version with `-mwindows`, which is fine for a GUI application but not for a CLI command (see [here](https://github.com/mpv-player/mpv/issues/58#issuecomment-15944500) for a quick explanation).

Later today I will prepare a new package without `-mwindows`, so that you can check if the problem goes away.

The drawback is that a terminal will pop-up each time the GUI version (without `--batch`) is started, but this is a Windows limitation I cannot overcome...

**Comment by aferrero2707** [comment] 2017-08-30 20:38
Could you please try [this new package](https://github.com/aferrero2707/PhotoFlow/releases/download/continuous/photoflow-w64-20170830-git-stable.zip) and see if it fixed the problem of batch processing? 

Thanks!

**Comment by phweyland** [comment] 2017-08-30 21:15
I've tried this new package but the behaviour is the same (immediately in the background).

**Comment by aferrero2707** [comment] 2017-08-31 09:59
My apologizes! I messed up with the commits, and as a result the new version was still compiled with the `-mwindows` switch! 

Today I made yet another package that should finally be OK (at least the `-mwindows` option did not show up in the g++ invocation). Could you grab it from [here](https://github.com/aferrero2707/PhotoFlow/releases/download/continuous/photoflow-w64-20170831-git-stable.zip)?

Thanks!

**Comment by phweyland** [comment] 2017-08-31 20:06
This time it is very verbose ! :-)
I send you the output because, as the for the first run the image did exist any more, Photoflow crashed.
I relaunched with an existing one, then it succeeded. Both runs are in the log file.

[Photoflow 20180831.txt](https://github.com/aferrero2707/PhotoFlow/files/1268336/Photoflow.20180831.txt)

**Comment by phweyland** [comment] 2017-09-01 09:44
Yes, the batch run did run on the foreground.

**Comment by aferrero2707** [comment] 2017-09-01 11:16
So I'm closing this issue and opening a new one concerning the improvement of the behaviour when the input file is missing.

Thanks!

**Closed by aferrero2707** 2017-09-01 11:16 UTC
Labels: bug
