### ISSUE TITLE
Arch Linux: crash opening CR2 files

### ISSUE THREAD

**Issue by Joermungand** [aferrero2707/PhotoFlow#173] opened 2018-01-23 10:19 UTC
Photoflow crashes (segfaults) when opening CR2 files. I’ve managed to trace the regression down to commit 30bc9c5b2b4a567a307b92816864f831084e9e26 on January 9th.
Please let me know what logs you need added.

**Comment by aferrero2707** [comment] 2018-01-23 11:20
I will first try to reproduce the issue with CR2 files I have, and eventually will ask for an example of failing RAW file if I do not see the crash...

Thanks!

**Comment by aferrero2707** [comment] 2018-01-23 15:15
Would you be able to compile photoflow with `-DCMAKE_BUILD_TYPE=RelWithDebInfo` cmake flag, run the program through `gdb` and provide me the full backtrace of the crash?

Also, could you provide me an example of failing CR2 file? I tried with few that I have, and I could never observe any crash...

Thanks!

**Comment by Joermungand** [comment] 2018-01-23 16:08
Sure, right away. It’ll take a while to compile, though. Meanwhile, an example it crashes with is right [here](https://www.dropbox.com/s/m4r0yawuw52z719/IMG_3602.CR2?dl=0).

**Comment by Joermungand** [comment] 2018-01-23 17:14
Here’s the backtrace. Hope it’s useful.
[bt-full.log](https://github.com/aferrero2707/PhotoFlow/files/1656916/bt-full.log)

**Comment by aferrero2707** [comment] 2018-01-23 18:13
Could you tell me the version of VIPS (or libvips) that is installed on your system? It might be some bug in VIPS itself...

**Comment by Joermungand** [comment] 2018-01-23 18:18
VIPS is currently at 8.6.1. As a matter of fact the crash occurred the same day as VIPS was updated from 8.5.9 – however, I doubt this should be the case, since I also tried downgrading VIPS to 8.5.9 and the result was exactly the same: no crash with Photoflow prior to that commit, crash from then on.

**Comment by aferrero2707** [comment] 2018-01-23 19:41
Interesting... in any case, the culprit seems to be the `vips_image_remove()` function, so I will dig into it.

**Comment by aferrero2707** [comment] 2018-01-23 21:07
I have just committed some additional diagnostics and, hopefully, a fix. Could you please update your sources and try again?

If it still fails, I would need the full terminal output after the crash...

Thanks!

**Comment by Joermungand** [comment] 2018-01-23 21:11
Yeah, looks like that to me. Please let me know if I can help in any way.

**Comment by Joermungand** [comment] 2018-01-23 21:11
On it.

**Comment by Joermungand** [comment] 2018-01-23 21:54
Crashed again. Here’s the complete log: [crash.log](https://github.com/aferrero2707/PhotoFlow/files/1657733/crash.log). Please let me know if you need the gdb backtrace.

**Comment by aferrero2707** [comment] 2018-01-23 21:56
> Please let me know if you need the gdb backtrace.

Yes, please!

**Comment by Joermungand** [comment] 2018-01-23 22:05
OK. Here’s the gdb log: [bt-full.log](https://github.com/aferrero2707/PhotoFlow/files/1657767/bt-full.log).
And here’s the terminal output of running gdb: [gdb-output.log](https://github.com/aferrero2707/PhotoFlow/files/1657769/gdb-output.log).

**Comment by aferrero2707** [comment] 2018-01-23 22:17
Thanks! I have hopefully finally found the mistake: the use of a deleted image (`out`) [here](https://github.com/aferrero2707/PhotoFlow/blob/stable/src/base/imagepyramid.cc#L360).

Please update again, and cross fingers...

**Comment by Joermungand** [comment] 2018-01-23 22:21
That would explain it. Updating.

**Comment by Joermungand** [comment] 2018-01-23 23:06
Yap. It looks like that was the culprit. Working fine now. Thanks a lot.

**Comment by aferrero2707** [comment] 2018-01-24 08:21
Good job, thanks a lot!

I'm closing the issue.

**Closed by aferrero2707** 2018-01-24 08:21 UTC
