### ISSUE TITLE
Zooming out fast crashes PhotoFlow (Windows 10 plus Kubuntu 19.10)

### ISSUE THREAD

**Issue by SilvioGrosso** [aferrero2707/PhotoFlow#204] opened 2019-10-31 22:49 UTC
This crash was already present in the past but lately it looked as though it was fixed...

With the latest build on Windows 10 (photoflow-w64-20191031_1335-git-stable-b4f3ba15b50c2f04d177b18dd9bbeaa40a82d9ba) and the latest AppImage on Kubuntu 19.10 (Kde desktop) it is extremely easy to always crash PhotoFlow while zooming out fast. 
No matter what image you try the crash always occur on both systems.

Here it a video (kubuntu 19.10):
https://www.dropbox.com/s/ngejowrk29v98yr/PHOTOFLOW_ZOOM-OUT-31-OTT.mp4?dl=0

Here is the log (Kubuntu 19.10):
https://www.dropbox.com/s/3cwcsa4vb6dq1lg/LOG_CRASH_zoom-out-kubuntu-windows.txt?dl=0

**Comment by aferrero2707** [comment] 2019-11-10 21:23
@SilvioGrosso this was fixed in the `enhanced-usm` branch with commit 065c4c63ccb341219c1e46320d590846c5f34b49, but I forgot to port the fix to the `stable` branch as well. Now it should be fine.

Could you please confirm?
Thanks!

**Comment by SilvioGrosso** [comment] 2019-11-10 21:45
> Now it should be fine.

It is not entirely clear to me in which version it should be fine... :-)
This being said, with the stable version (Windows 10):
photoflow-w64-20191109_1805-git-stable-0172654e272c5b270586492435d86ec8b441580e
It is still extremely easy to crash PhotoFlow no matter what image you try. As usual, you only need to zoom out *very* fast.

BTW, why don't you work with a single branch?
Please, don't get me wrong. I am totallly aware the "right" way should be having more branches. 
Each one useful for testing new *different* things...
However, this sound approach is very time consuming for you (in terms of time especially). 
IMHO, It is also confusing for users because they are supposed to always choose among many versions available in a web-page extremely cluttered as of today...

Just to give an example: with Db Browser for Sqlite [1] there are nightly builds where you can test the new stuff, just releasd. However, there is only one version to test. Needless to say, the new features may be extremely dangerous, stability-wise, but you only need to revert to the stable version or to some previous build to avoid this negative side-effect.

[1] https://nightlies.sqlitebrowser.org/latest/

**Comment by SilvioGrosso** [comment] 2019-11-10 22:11
Ok.
Just tested on Windows 10:
photoflow-w64-20191108_2139-git-enhanced-usm-8493d326c3b0714a815a167f234170071f659f43

It does not crash while zooming out very fast.
Tested several images.

**Comment by aferrero2707** [comment] 2019-11-10 23:35
Reopening because the fix in the stable branch is not yet confirmed.

@SilvioGrosso could you also try with https://github.com/aferrero2707/PhotoFlow/releases/download/continuous/photoflow-w64-20191110_2200-git-stable-b75d36e275105cf7acf528d57dc84b5384919e22.zip?

Concerning the packages, I agree and I am setting up a mechanism to automatically clean up the release page and only keep the most recent package.
I have also mostly worked with a single branch in the past, but in some cases I have preferred to opt for dedicated branches for features under development. It is a bit more work, but helps keep the code and development cleaner on my side.
That said, I will put all the new stuff into stable very soon, and work solely on bug fixes in order to prepare a new "official" release...

**Comment by SilvioGrosso** [comment] 2019-11-11 17:26
Just tested your last ZIP Installer on Windows 10
No crash whatsoever while zooming out.
No problem when opening and closing many images consecutively.

Great work indeed! :-)

We can close this ticket now...

**Closed as completed** 2019-11-11 17:29 UTC
